version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./dev.sqlite
      - SESSION_SECRET=your-session-secret-here
      - SHOPIFY_API_KEY=your-api-key
      - SHOPIFY_API_SECRET=your-api-secret
      - SHOPIFY_APP_URL=http://localhost:3000
      - SCOPES=write_products,read_all_orders,read_products,write_orders,read_locations,write_order_edits
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    command: npm run dev

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=reverse_bundle
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: