name = "remix"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "npx prisma generate --schema=prisma/schema.production.prisma"
dev = "npm run setup:prod && npm exec remix vite:dev"
