# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "71fd9bfaa51d9b70a3b6511192fafe4b"
name = "reverse-bundling"
application_url = "https://reverse-bundle-pro.fly.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_products"

[auth]
redirect_urls = [
  "https://reverse-bundle-pro.fly.dev/auth/callback",
  "https://reverse-bundle-pro.fly.dev/auth/shopify/callback",
  "https://reverse-bundle-pro.fly.dev/api/auth/callback"
]
