# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "784665a29510303d56391f0df4fcf21d"
name = "Reverse Bundle Pro"
application_url = "https://reversebundling.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,read_products"

[auth]
redirect_urls = [ "https://reversebundling.app/api/auth" ]
