# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "34cb9a0e91e7c069ba308f2d7bc27f52"
name = "reverse-bundling"
application_url = "https://reverse-bundle-pro.fly.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_products"

[auth]
redirect_urls = [
  "https://reverse-bundle-pro.fly.dev/auth/callback",
  "https://reverse-bundle-pro.fly.dev/auth/shopify/callback",
  "https://reverse-bundle-pro.fly.dev/api/auth/callback"
]
